# Site settings
title: Gianadda
copyright: Copyright © 2013-2015
author: Perry Productions
author_url: https://www.perry.productions/
description: A static gallery generator for hikers and bikers
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gianadda.perry.productions" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
analytics: UA-55206549-4

social:
-   icon: linkedin
    title: Linked in
    url: "https://www.linkedin.com/in/mauriceperry"
-   icon: gplus
    title: Google+
    url: "https://plus.google.com/105003383502499251992/"
-   icon: github
    title: Githup
    url: "https://github.com/robbyn"
-   icon: stackoverflow
    title: StackOverflow
    url: "http://stackoverflow.com/users/72673/maurice-perry"

nav:
-   title: Usage
    url: "/Usage.html"
-   title: Themes
    url: "/Themes/"
-   title: Generated files
    url: "/GeneratedFiles.html"
