# Site settings
title: Gianadda
copyright: Copyright © 2013-2015
author: Perry Productions
author_url: https://www.perry.productions/
description: > # A gallery generator for hikers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gianadda.perry.productions" # the base hostname & protocol for your site
github_username:  robbyn
linkedin_username: mauriceperry

# Build settings
markdown: kramdown
analytics: UA-55206549-4
